

efs:
  enabled: true
  fsid: fs-12345
  #subPath: demo  # projekt verzeichnis, default release name
  extraDirs:
    - pluginA
    - pluginB

nginx:
  extraVolumeMounts:
    - name: test123-volume
      mountPath: /var/www/html/web/app/test123
      readOnly: true

php:
  extraVolumeMounts:
    - name: test123-volume
      mountPath: /var/www/html/web/app/test123
      readOnly: false
    - name: efs
      mountPath: /var/www/html/web/app
      readOnly: false
    - name: efs
      mountPath: /var/www/html/web/app/pluginA
      subPath: pluginA
      readOnly: false
    - name: efs
      mountPath: /var/www/html/web/app/pluginB
      subPath: pluginB
      readOnly: false

externalSecrets:
  enabled: true
  #engine: kube-external-secrets
  engine: external-secrets
  region: eu-central-1
  backendType: systemManager
  env:
    DB_ROOT_USERNAME: /dev/wordpress-1/DB/username
    DB_ROOT_PASSWORD: /dev/wordpress-1/DB/password
    DB_USERNAME: /dev/exampleblog/DB/username
    DB_PASSWORD: /dev/exampleblog/DB/password
    WORDPRESS_USERNAME: /dev/exampleblog/wordpress/username
    WORDPRESS_PASSWORD: /dev/exampleblog/wordpress/password
    TESTZEUGS: /dev/exampleblog/wordpress/testzeugs

env:
  DB_NAME: bedrocksample

hpa:
  engine: keda
  httpAddon:
    enabled: true

ingress:
  enabled: true
  hosts:
  - host: www.example.com

cron:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  php:
    memory_limit: 128M
  jobs:
    job1:
      enabled: true
      timeZone: Etc/UTC
      schedule: "*/5 * * * *"
      command: wp --version
      concurrencyPolicy: Replace
      restartPolicy: OnFailure
      backoffLimit: 2
      startingDeadlineSeconds: 1800
    that-is-a-very-long-job-name:
      enabled: true
      schedule: "* 16 * * 5"
      command: /var/www/html/web/app/plugins/regular_task.sh
      resources:
        limits:
          memory: 2048Mi
        requests:
          cpu: 100m
          memory: 512Mi
      php:
        memory_limit: 512M
    job3:
      enabled: false
      schedule: "* 15 * * 5"
      command: /scripts/to_something.sh

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the release name
  name: test-project
  iamRoleArn: arn:aws:iam::123456789012:role/test-project-role

automaticZonePlacement:
  enabled: true
  spreadInstancesTypes: false
  fqdn: wordpress.rds.cloud.internal