name: Build and Publish Helm Chart on Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml
    secrets: inherit

  build-and-push:
    runs-on: arvato
    permissions:
      id-token: write
      contents: write  # Needed to update the VERSION file
      packages: write

    env:
      HELM_VERSION: v3.19.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install helm
        run: |
          wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-arm64.tar.gz
          tar -zxvf helm-${HELM_VERSION}-linux-arm64.tar.gz
          sudo mv linux-arm64/helm /usr/local/bin/helm
          rm -rf helm-${HELM_VERSION}-linux-arm64.tar.gz linux-arm64

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run helm show chart
        run: |
          helm show chart .

      - name: Run helm lint
        run: |
          helm lint .

      - name: Commit Updated linted files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Linted files"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Package Helm Chart
        run: |
          helm package . --destination ./charts

      # - name: Push Docker Image to GHCR
      #   run: |
      #     helm push ./charts/*.tgz oci://ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
